wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.15
    t:
      1:
      - 5
      2:
      - 5
      4: 3.9.15
      5: 0.10.31
      8:
      - 5
mlflow_model:
  desc: null
  value: random_forest_export:prod
test_dataset:
  desc: null
  value: test_data.csv:latest
