wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.15
    session_history: code/_session_history.ipynb
    start_time: 1669244004.840876
    t:
      1:
      - 55
      2:
      - 53
      - 55
      3:
      - 2
      - 23
      4: 3.8.15
      5: 0.13.5
      8:
      - 1
      - 5
