wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1669659811.644239
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.9.15
      5: 0.13.5
      8:
      - 5
input:
  desc: null
  value: clean_sample.csv:latest
random_seed:
  desc: null
  value: 42
stratify_by:
  desc: null
  value: neighbourhood_group
test_size:
  desc: null
  value: 0.2
